language: php

sudo: false

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update

before_script:
  - travis_retry composer install

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpcpd --exclude tests src/
  - ./vendor/bin/phpmd src/ text codesize,unusedcode --suffixes .php
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: 5.4

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  email: false